// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo7lvoHnhriLQMEQoZTGpfL4gJGYB3Tg4',
    appId: '1:235624574354:web:b32c64e6672f6ce0f2e54b',
    messagingSenderId: '235624574354',
    projectId: 'to-do-list-d612a',
    authDomain: 'to-do-list-d612a.firebaseapp.com',
    storageBucket: 'to-do-list-d612a.appspot.com',
    measurementId: 'G-5Y9SHF45QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkSxI2fXH8ppHn4_UqbaIs3B4vVGI1CNI',
    appId: '1:235624574354:android:0f641bdfabe12fe3f2e54b',
    messagingSenderId: '235624574354',
    projectId: 'to-do-list-d612a',
    storageBucket: 'to-do-list-d612a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEvLXSuIyomMSC4PK7zbUXa4dTux523So',
    appId: '1:235624574354:ios:9984cd5e33261a23f2e54b',
    messagingSenderId: '235624574354',
    projectId: 'to-do-list-d612a',
    storageBucket: 'to-do-list-d612a.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEvLXSuIyomMSC4PK7zbUXa4dTux523So',
    appId: '1:235624574354:ios:9984cd5e33261a23f2e54b',
    messagingSenderId: '235624574354',
    projectId: 'to-do-list-d612a',
    storageBucket: 'to-do-list-d612a.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo7lvoHnhriLQMEQoZTGpfL4gJGYB3Tg4',
    appId: '1:235624574354:web:2c0f366cc55b1414f2e54b',
    messagingSenderId: '235624574354',
    projectId: 'to-do-list-d612a',
    authDomain: 'to-do-list-d612a.firebaseapp.com',
    storageBucket: 'to-do-list-d612a.appspot.com',
    measurementId: 'G-3S7DRKQTF7',
  );
}
